/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "ratemeter.v:1" *)
module ratemeter(clk, pulse, rst, outmeter, outcnt);
  (* src = "ratemeter.v:19" *)
  wire [3:0] _00_;
  (* src = "ratemeter.v:19" *)
  wire _01_;
  (* src = "ratemeter.v:32" *)
  wire [3:0] _02_;
  (* src = "ratemeter.v:39" *)
  wire [3:0] _03_;
  (* src = "ratemeter.v:23" *)
  (* unused_bits = "4" *)
  wire [31:0] _04_;
  (* src = "ratemeter.v:36" *)
  (* unused_bits = "4" *)
  wire [31:0] _05_;
  (* src = "ratemeter.v:43" *)
  (* unused_bits = "4" *)
  wire [31:0] _06_;
  (* src = "ratemeter.v:23|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3" *)
  wire [31:0] _07_;
  (* src = "ratemeter.v:36|ratemeter.v:23|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3" *)
  wire [31:0] _08_;
  (* src = "ratemeter.v:43|ratemeter.v:23|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3" *)
  wire [31:0] _09_;
  (* src = "ratemeter.v:25|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [31:0] _10_;
  wire [31:0] _11_;
  (* src = "ratemeter.v:23|<techmap.v>:260|<techmap.v>:222" *)
  wire _12_;
  (* src = "ratemeter.v:25|<techmap.v>:260|<techmap.v>:221" *)
  wire _13_;
  (* src = "ratemeter.v:11" *)
  input clk;
  (* src = "ratemeter.v:17" *)
  reg [3:0] cnt_meter;
  (* src = "ratemeter.v:18" *)
  reg enable_meter;
  (* src = "ratemeter.v:14" *)
  output [3:0] outcnt;
  reg [3:0] outcnt;
  (* src = "ratemeter.v:15" *)
  output [3:0] outmeter;
  reg [3:0] outmeter;
  (* src = "ratemeter.v:12" *)
  input pulse;
  (* src = "ratemeter.v:13" *)
  input rst;
  assign _03_[0] = enable_meter ? (* src = "ratemeter.v:40" *) _06_[0] : 1'h0;
  assign _03_[1] = enable_meter ? (* src = "ratemeter.v:40" *) _06_[1] : 1'h0;
  assign _03_[2] = enable_meter ? (* src = "ratemeter.v:40" *) _06_[2] : 1'h0;
  assign _03_[3] = enable_meter ? (* src = "ratemeter.v:40" *) _06_[3] : 1'h0;
  assign _02_[0] = rst ? (* src = "ratemeter.v:33" *) _05_[0] : 1'h0;
  assign _02_[1] = rst ? (* src = "ratemeter.v:33" *) _05_[1] : 1'h0;
  assign _02_[2] = rst ? (* src = "ratemeter.v:33" *) _05_[2] : 1'h0;
  assign _02_[3] = rst ? (* src = "ratemeter.v:33" *) _05_[3] : 1'h0;
  assign _00_[0] = rst ? (* src = "ratemeter.v:20" *) _04_[0] : 1'h0;
  assign _00_[1] = rst ? (* src = "ratemeter.v:20" *) _04_[1] : 1'h0;
  assign _00_[2] = rst ? (* src = "ratemeter.v:20" *) _04_[2] : 1'h0;
  assign _00_[3] = rst ? (* src = "ratemeter.v:20" *) _04_[3] : 1'h0;
  assign _01_ = ~(* src = "ratemeter.v:25" *) _10_[31];
  (* src = "ratemeter.v:32" *)
  always @(posedge pulse)
      outcnt[3] <= _02_[3];
  (* src = "ratemeter.v:19" *)
  always @(posedge clk)
      cnt_meter[0] <= _00_[0];
  (* src = "ratemeter.v:19" *)
  always @(posedge clk)
      cnt_meter[1] <= _00_[1];
  (* src = "ratemeter.v:19" *)
  always @(posedge clk)
      cnt_meter[2] <= _00_[2];
  (* src = "ratemeter.v:19" *)
  always @(posedge clk)
      cnt_meter[3] <= _00_[3];
  (* src = "ratemeter.v:19" *)
  always @(posedge clk)
      enable_meter <= _01_;
  (* src = "ratemeter.v:39" *)
  always @(posedge pulse)
      outmeter[0] <= _03_[0];
  (* src = "ratemeter.v:39" *)
  always @(posedge pulse)
      outmeter[1] <= _03_[1];
  (* src = "ratemeter.v:39" *)
  always @(posedge pulse)
      outmeter[2] <= _03_[2];
  (* src = "ratemeter.v:39" *)
  always @(posedge pulse)
      outmeter[3] <= _03_[3];
  (* src = "ratemeter.v:32" *)
  always @(posedge pulse)
      outcnt[0] <= _02_[0];
  (* src = "ratemeter.v:32" *)
  always @(posedge pulse)
      outcnt[1] <= _02_[1];
  (* src = "ratemeter.v:32" *)
  always @(posedge pulse)
      outcnt[2] <= _02_[2];
  assign _07_[2] = cnt_meter[2] &(* src = "ratemeter.v:23|<techmap.v>:260|<techmap.v>:229" *)  _07_[1];
  assign _09_[1] = outmeter[1] &(* src = "ratemeter.v:43|ratemeter.v:23|<techmap.v>:260|<techmap.v>:221" *)  outmeter[0];
  assign _09_[2] = outmeter[2] &(* src = "ratemeter.v:43|ratemeter.v:23|<techmap.v>:260|<techmap.v>:229" *)  _09_[1];
  assign _13_ = _11_[1] &(* src = "ratemeter.v:25|<techmap.v>:260|<techmap.v>:221" *)  cnt_meter[0];
  assign _10_[31] = _12_ &(* src = "ratemeter.v:25|<techmap.v>:260|<techmap.v>:221" *)  _10_[1];
  assign _12_ = cnt_meter[3] &(* src = "ratemeter.v:25|<techmap.v>:260|<techmap.v>:222" *)  cnt_meter[2];
  assign _10_[1] = cnt_meter[1] |(* src = "ratemeter.v:25|<techmap.v>:260|<techmap.v>:221" *)  _13_;
  assign _08_[1] = outcnt[1] &(* src = "ratemeter.v:36|ratemeter.v:23|<techmap.v>:260|<techmap.v>:221" *)  outcnt[0];
  assign _04_[1] = cnt_meter[1] ^(* src = "ratemeter.v:23|<techmap.v>:263" *)  cnt_meter[0];
  assign _04_[2] = cnt_meter[2] ^(* src = "ratemeter.v:23|<techmap.v>:263" *)  _07_[1];
  assign _04_[3] = cnt_meter[3] ^(* src = "ratemeter.v:23|<techmap.v>:263" *)  _07_[2];
  assign _08_[2] = outcnt[2] &(* src = "ratemeter.v:36|ratemeter.v:23|<techmap.v>:260|<techmap.v>:229" *)  _08_[1];
  assign _06_[1] = outmeter[1] ^(* src = "ratemeter.v:43|ratemeter.v:23|<techmap.v>:263" *)  outmeter[0];
  assign _06_[2] = outmeter[2] ^(* src = "ratemeter.v:43|ratemeter.v:23|<techmap.v>:263" *)  _09_[1];
  assign _06_[3] = outmeter[3] ^(* src = "ratemeter.v:43|ratemeter.v:23|<techmap.v>:263" *)  _09_[2];
  assign _06_[0] = outmeter[0] ^(* src = "ratemeter.v:43|ratemeter.v:23|<techmap.v>:262" *)  1'h1;
  assign _04_[0] = cnt_meter[0] ^(* src = "ratemeter.v:25|<techmap.v>:263" *)  1'h1;
  assign _11_[1] = cnt_meter[1] ^(* src = "ratemeter.v:25|<techmap.v>:262" *)  1'h1;
  assign _05_[1] = outcnt[1] ^(* src = "ratemeter.v:36|ratemeter.v:23|<techmap.v>:263" *)  outcnt[0];
  assign _05_[2] = outcnt[2] ^(* src = "ratemeter.v:36|ratemeter.v:23|<techmap.v>:263" *)  _08_[1];
  assign _05_[3] = outcnt[3] ^(* src = "ratemeter.v:36|ratemeter.v:23|<techmap.v>:263" *)  _08_[2];
  assign _05_[0] = outcnt[0] ^(* src = "ratemeter.v:36|ratemeter.v:23|<techmap.v>:262" *)  1'h1;
  assign _07_[1] = cnt_meter[1] &(* src = "ratemeter.v:23|<techmap.v>:260|<techmap.v>:221" *)  cnt_meter[0];
  assign _04_[31:5] = 27'h0000000;
  assign _05_[31:5] = 27'h0000000;
  assign _06_[31:5] = 27'h0000000;
  assign { _07_[31:3], _07_[0] } = { 28'h0000000, _04_[4], cnt_meter[0] };
  assign { _08_[31:3], _08_[0] } = { 28'h0000000, _05_[4], outcnt[0] };
  assign { _09_[31:3], _09_[0] } = { 28'h0000000, _06_[4], outmeter[0] };
  assign { _10_[30:3], _10_[0] } = { _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], _10_[31], cnt_meter[0] };
  assign { _11_[31:2], _11_[0] } = { 28'hfffffff, cnt_meter[3:2], cnt_meter[0] };
endmodule
